### ISSUE TITLE
Not working with vscode

### ISSUE THREAD

**Issue by james-tindal** [jsr-io/jsr-npm#104]
I followed the instructions here: [jsr.io/docs/npm-compatibility](https://jsr.io/docs/npm-compatibility)
to install @decorators/bind using pnpm
vscode tells me "Cannot find module '@decorators/bind' or its corresponding type declarations"

Also it didn't detect my pnpm-lock.yaml and tried installing with npm

# Solved

Set tsconfig moduleResolution to 'node16', 'nodenext', or 'bundler'

**Comment by marvinhagemeister** [comment]
Thanks for letting us know! I've made a PR to prefer the lockfile detection over the used package manager when running the jsr binary (#105).

Regarding the missing declaration files: That is to be expected and the way TypeScript works. Nothing we can change about that. Quoting the [TypeScript docs](https://www.typescriptlang.org/tsconfig/#moduleResolution):

> `node16` or `nodenext` for modern versions of Node.js. Node.js v12 and later supports both ECMAScript imports and CommonJS require, which resolve using different algorithms. 
>
> `node10` (previously called `node`) for Node.js versions older than v10, which only support CommonJS require. You probably won’t need to use node10 in modern code.

Or in other words: If you're developing a Node project with TypeScript you should always use one of `node16`, `nodenext` or `bundler` and never `node` or `node10`.
