### ISSUE TITLE
`npx jsr <subcommand>` exits with `0` for unknown commands

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jsr-io/jsr-npm#79]
I tried running `npx jsr init` to see if it did something. `init` is not supported (so it did nothing), but it exists with `0` rather than a non-0 exit code.

**Comment by nicolo-ribaudo** [comment]
I just tried again and I _now_ also get 1 with an error:

![image](https://github.com/jsr-io/jsr-npm/assets/7000710/948b1017-590d-470f-a51b-09b7450bc327)

Luckily I still have my terminal opened for yesterday, and I can guarantee that the command was not failing :sweat_smile: 

![image](https://github.com/jsr-io/jsr-npm/assets/7000710/fb05480c-5e14-4714-aa6c-da7139f53d3c)

**Comment by nicolo-ribaudo** [comment]
Oh I can reproduce it again, it happens if you do not already have a `package.json` file.

**Comment by marvinhagemeister** [comment]
Yup that's it. Can confirm this bug.
