### ISSUE TITLE
Error publishing package using node:readline/promises

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [jsr-io/jsr-npm#91]
No idea if this is where I should post the issue. I get an error when trying to publish my simple package to JSR:

```
$ npx jsr publish
Need to install the following packages:
jsr@0.12.4
Ok to proceed? (y) y

Downloading JSR binary...
[00:01] [#################################################>] 37.4 MiB/37.5 MiB
error: Unknown built-in "node:" module: readline/promises
    at file:///C:/Github/my-libraries/hvb-screenshots/dist/dist.js:9:22
Child process exited with: 1
```

Am I missing something?

Repro: https://github.com/henrikvilhelmberglund/hvb-screenshots

**Comment by bartlomieju** [comment]
It's actually a bug in Deno, I opened https://github.com/denoland/deno/pull/24336 to fix this problem.

**Comment by henrikvilhelmberglund** [comment]
> It's actually a bug in Deno, I opened [denoland/deno#24336](https://github.com/denoland/deno/pull/24336) to fix this problem.

Thanks!

**Comment by bartlomieju** [comment]
@marvinhagemeister is the `jsr-npm` using canary version of Deno?

**Comment by marvinhagemeister** [comment]
yes
