### ISSUE TITLE
JSR Command fails on Windows

### ISSUE THREAD

**Issue by louiss0** [jsr-io/jsr-npm#98]
OS: Windows 
Package Manager: pnpm

I tried to run jsr using `npm dlx jsr publish` but I got this

```sh 
 npx jsr publish --dry-run
Need to install the following packages:
jsr@0.12.4
Ok to proceed? (y) Y

Downloading JSR binary...
[00:00] [#################################################>] 37.2 MiB/37.6 MiB
'C:\Users\Venel' is not recognized as an internal or external command,
operable program or batch file.
Child process exited with: 1
```

It has something to do with windows path but I don't know if I can fix this I might have to install jsr instead.
Link to minimal reproducible example: https://github.com/louiss0/dummy-jsr

**Comment by marvinhagemeister** [comment]
Tried to reproduce the described error on my windows machine, but I'm not able to. It works as expected and publishes the package.

**Comment by louiss0** [comment]
> Tried to reproduce the described error on my windows machine, but I'm not able to. It works as expected and publishes the package.

I realized that it has something to do with the path. 

The path on Windows is.
```sh
C:\Users\Venel Louis\Desktop
```

**Comment by marvinhagemeister** [comment]
Tried with a folder that contains spaces, but still can't reproduce it. Publishing works as expected. Tried both with PowerShell and the old `cmd.exe`.

**Comment by louiss0** [comment]
I guess it had something to do with my computer
